/********************************************************************************
** Form generated from reading UI file 'paint.ui'
**
** Created by: Qt User Interface Compiler version 6.5.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PAINT_H
#define UI_PAINT_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_paint
{
public:
    QWidget *centralwidget;
    QLabel *chara;
    QLabel *chara_2;
    QLabel *chara_3;
    QLabel *chara_4;
    QLabel *chara_5;
    QLabel *chara_6;
    QLabel *chara_7;
    QLabel *chara_8;
    QLabel *chara_9;
    QLabel *chara_10;
    QLabel *chara_11;
    QLabel *chara_12;
    QLabel *chara_23;
    QLabel *chara_24;
    QLabel *chara_25;
    QLabel *chara_26;
    QLabel *chara_27;
    QLabel *chara_28;
    QLabel *chara_30;
    QLabel *chara_31;
    QLabel *chara_32;
    QLabel *chara_13;
    QLabel *chara_14;
    QLabel *chara_15;
    QLabel *chara_16;
    QLabel *chara_17;
    QLabel *chara_18;
    QLabel *chara_19;
    QLabel *chara_20;
    QLabel *chara_21;
    QLabel *chara_22;
    QLabel *chara_29;
    QLabel *chara_33;
    QLabel *chara_34;
    QLabel *chara_35;
    QLabel *chara_36;
    QLabel *chara_37;
    QLabel *chara_38;
    QLabel *chara_39;
    QLabel *chara_40;
    QLabel *chara_41;
    QLabel *chara_42;
    QLabel *chara_43;
    QLabel *chara_44;
    QLabel *chara_45;
    QLabel *chara_46;
    QLabel *chara_47;
    QLabel *chara_48;
    QLabel *chara_49;
    QLabel *chara_50;
    QLabel *chara_51;
    QLabel *chara_52;
    QLabel *chara_53;
    QLabel *chara_54;
    QLabel *chara_55;
    QLabel *chara_56;
    QLabel *chara_57;
    QLabel *chara_58;
    QLabel *chara_59;
    QLabel *chara_60;
    QLabel *chara_61;
    QLabel *chara_62;
    QLabel *chara_63;
    QLabel *chara_64;
    QLabel *chara_65;
    QLabel *chara_66;
    QLabel *chara_67;
    QLabel *chara_68;
    QLabel *chara_69;
    QLabel *chara_70;
    QLabel *chara_71;
    QLabel *chara_72;
    QLabel *chara_73;
    QLabel *chara_74;
    QLabel *chara_75;
    QLabel *chara_76;
    QLabel *chara_77;
    QLabel *chara_78;
    QLabel *chara_79;
    QLabel *chara_80;
    QLabel *chara_81;
    QLabel *chara_82;
    QLabel *chara_83;
    QLabel *chara_84;
    QLabel *chara_85;
    QLabel *chara_86;
    QLabel *chara_87;
    QLabel *chara_88;
    QLabel *chara_89;
    QLabel *chara_90;
    QLabel *chara_91;
    QLabel *chara_92;
    QLabel *chara_93;
    QLabel *chara_94;
    QLabel *chara_95;
    QLabel *chara_96;
    QLabel *chara_97;
    QLabel *chara_98;
    QLabel *chara_99;
    QLabel *chara_100;
    QLabel *chara_101;
    QLabel *chara_102;
    QLabel *chara_103;
    QLabel *chara_104;
    QLabel *chara_105;
    QLabel *chara_106;
    QLabel *chara_107;
    QLabel *chara_108;
    QLabel *chara_109;
    QLabel *chara_110;
    QLabel *chara_111;
    QLabel *chara_112;
    QLabel *chara_113;
    QLabel *chara_114;
    QLabel *chara_115;
    QLabel *chara_116;
    QLabel *chara_117;
    QLabel *chara_118;
    QLabel *chara_119;
    QLabel *arbusto9;
    QLabel *arbusto3;
    QLabel *arbusto4;
    QLabel *arbusto8;
    QLabel *arbusto5;
    QLabel *arbusto6;
    QLabel *arbusto7;
    QLabel *arbusto1;
    QLabel *arbusto2;
    QLabel *semaforo;
    QLabel *semaforo_2;
    QLabel *enemy;
    QLabel *enemy_2;
    QLabel *enemy_3;
    QLabel *yellow;
    QLabel *arbusto5_2;
    QLabel *arbusto5_3;
    QLabel *arbusto5_4;
    QLabel *arbusto5_5;
    QLabel *arbusto5_6;
    QLabel *arbusto5_7;
    QLabel *arbusto5_8;
    QLabel *arbusto5_9;
    QLabel *arbusto5_10;
    QLabel *arbusto5_11;
    QLabel *arbusto5_12;
    QLabel *arbusto5_13;
    QLabel *arbusto5_14;
    QLabel *arbusto5_15;
    QLabel *arbusto5_16;
    QLabel *arbusto5_17;
    QLabel *arbusto5_18;
    QLabel *arbusto5_19;
    QLabel *arbusto5_20;
    QLabel *arbusto5_21;
    QLabel *arbusto5_22;
    QLabel *arbusto5_23;
    QLabel *arbusto5_24;
    QLabel *arbusto5_25;
    QLabel *arbusto5_26;
    QLabel *arbusto5_27;
    QLabel *arbusto5_28;
    QLabel *arbusto5_29;
    QLabel *arbusto5_30;
    QLabel *arbusto5_31;
    QLabel *arbusto5_32;
    QLabel *arbusto5_33;
    QLabel *arbusto5_34;
    QLabel *arbusto5_35;
    QLabel *arbusto5_36;
    QLabel *arbusto5_37;
    QLabel *arbusto5_38;
    QLabel *arbusto5_39;
    QLabel *arbusto5_40;
    QLabel *arbusto5_41;
    QLabel *arbusto5_42;
    QLabel *arbusto5_43;
    QLabel *arbusto5_44;
    QLabel *arbusto5_45;
    QLabel *arbusto5_46;
    QLabel *arbusto6_2;
    QLabel *arbusto6_3;
    QLabel *arbusto6_4;
    QLabel *arbusto6_5;
    QLabel *arbusto6_6;
    QLabel *arbusto6_7;
    QLabel *arbusto6_8;
    QLabel *arbusto6_9;
    QLabel *arbusto6_10;
    QLabel *arbusto6_11;
    QLabel *point;
    QLabel *menu;
    QPushButton *exit;
    QPushButton *play;
    QLabel *xplositon;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *paint)
    {
        if (paint->objectName().isEmpty())
            paint->setObjectName("paint");
        paint->resize(526, 352);
        centralwidget = new QWidget(paint);
        centralwidget->setObjectName("centralwidget");
        chara = new QLabel(centralwidget);
        chara->setObjectName("chara");
        chara->setGeometry(QRect(253, 308, 23, 23));
        chara->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia__2_-removebg-preview.png")));
        chara->setScaledContents(true);
        chara_2 = new QLabel(centralwidget);
        chara_2->setObjectName("chara_2");
        chara_2->setGeometry(QRect(160, 292, 181, 41));
        chara_2->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia__3_-removebg-preview.png")));
        chara_2->setScaledContents(true);
        chara_3 = new QLabel(centralwidget);
        chara_3->setObjectName("chara_3");
        chara_3->setGeometry(QRect(160, 260, 181, 41));
        chara_3->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia__3_-removebg-preview.png")));
        chara_3->setScaledContents(true);
        chara_4 = new QLabel(centralwidget);
        chara_4->setObjectName("chara_4");
        chara_4->setGeometry(QRect(160, 228, 181, 41));
        chara_4->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia__3_-removebg-preview.png")));
        chara_4->setScaledContents(true);
        chara_5 = new QLabel(centralwidget);
        chara_5->setObjectName("chara_5");
        chara_5->setGeometry(QRect(160, 196, 181, 41));
        chara_5->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia__3_-removebg-preview.png")));
        chara_5->setScaledContents(true);
        chara_6 = new QLabel(centralwidget);
        chara_6->setObjectName("chara_6");
        chara_6->setGeometry(QRect(160, 164, 181, 41));
        chara_6->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia__3_-removebg-preview.png")));
        chara_6->setScaledContents(true);
        chara_7 = new QLabel(centralwidget);
        chara_7->setObjectName("chara_7");
        chara_7->setGeometry(QRect(160, 100, 181, 41));
        chara_7->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia__3_-removebg-preview.png")));
        chara_7->setScaledContents(true);
        chara_8 = new QLabel(centralwidget);
        chara_8->setObjectName("chara_8");
        chara_8->setGeometry(QRect(160, 132, 181, 41));
        chara_8->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia__3_-removebg-preview.png")));
        chara_8->setScaledContents(true);
        chara_9 = new QLabel(centralwidget);
        chara_9->setObjectName("chara_9");
        chara_9->setGeometry(QRect(160, 68, 181, 41));
        chara_9->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia__3_-removebg-preview.png")));
        chara_9->setScaledContents(true);
        chara_10 = new QLabel(centralwidget);
        chara_10->setObjectName("chara_10");
        chara_10->setGeometry(QRect(160, 36, 181, 41));
        chara_10->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia__3_-removebg-preview.png")));
        chara_10->setScaledContents(true);
        chara_11 = new QLabel(centralwidget);
        chara_11->setObjectName("chara_11");
        chara_11->setGeometry(QRect(160, 5, 181, 41));
        chara_11->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia__3_-removebg-preview.png")));
        chara_11->setScaledContents(true);
        chara_12 = new QLabel(centralwidget);
        chara_12->setObjectName("chara_12");
        chara_12->setGeometry(QRect(160, -23, 181, 41));
        chara_12->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia__3_-removebg-preview.png")));
        chara_12->setScaledContents(true);
        chara_23 = new QLabel(centralwidget);
        chara_23->setObjectName("chara_23");
        chara_23->setGeometry(QRect(540, 250, 21, 21));
        chara_23->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (4).jpg")));
        chara_23->setScaledContents(true);
        chara_24 = new QLabel(centralwidget);
        chara_24->setObjectName("chara_24");
        chara_24->setGeometry(QRect(654, 250, 21, 21));
        chara_24->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (4).jpg")));
        chara_24->setScaledContents(true);
        chara_25 = new QLabel(centralwidget);
        chara_25->setObjectName("chara_25");
        chara_25->setGeometry(QRect(694, 250, 21, 21));
        chara_25->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (4).jpg")));
        chara_25->setScaledContents(true);
        chara_26 = new QLabel(centralwidget);
        chara_26->setObjectName("chara_26");
        chara_26->setGeometry(QRect(620, 250, 21, 21));
        chara_26->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (4).jpg")));
        chara_26->setScaledContents(true);
        chara_27 = new QLabel(centralwidget);
        chara_27->setObjectName("chara_27");
        chara_27->setGeometry(QRect(634, 250, 21, 21));
        chara_27->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (4).jpg")));
        chara_27->setScaledContents(true);
        chara_28 = new QLabel(centralwidget);
        chara_28->setObjectName("chara_28");
        chara_28->setGeometry(QRect(560, 250, 21, 21));
        chara_28->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (4).jpg")));
        chara_28->setScaledContents(true);
        chara_30 = new QLabel(centralwidget);
        chara_30->setObjectName("chara_30");
        chara_30->setGeometry(QRect(674, 250, 21, 21));
        chara_30->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (4).jpg")));
        chara_30->setScaledContents(true);
        chara_31 = new QLabel(centralwidget);
        chara_31->setObjectName("chara_31");
        chara_31->setGeometry(QRect(580, 250, 21, 21));
        chara_31->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (4).jpg")));
        chara_31->setScaledContents(true);
        chara_32 = new QLabel(centralwidget);
        chara_32->setObjectName("chara_32");
        chara_32->setGeometry(QRect(600, 250, 21, 21));
        chara_32->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (4).jpg")));
        chara_32->setScaledContents(true);
        chara_13 = new QLabel(centralwidget);
        chara_13->setObjectName("chara_13");
        chara_13->setGeometry(QRect(330, 0, 44, 41));
        chara_13->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_13->setScaledContents(true);
        chara_14 = new QLabel(centralwidget);
        chara_14->setObjectName("chara_14");
        chara_14->setGeometry(QRect(330, 30, 44, 41));
        chara_14->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_14->setScaledContents(true);
        chara_15 = new QLabel(centralwidget);
        chara_15->setObjectName("chara_15");
        chara_15->setGeometry(QRect(330, 60, 44, 41));
        chara_15->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_15->setScaledContents(true);
        chara_16 = new QLabel(centralwidget);
        chara_16->setObjectName("chara_16");
        chara_16->setGeometry(QRect(330, 100, 44, 41));
        chara_16->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_16->setScaledContents(true);
        chara_17 = new QLabel(centralwidget);
        chara_17->setObjectName("chara_17");
        chara_17->setGeometry(QRect(330, 140, 44, 41));
        chara_17->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_17->setScaledContents(true);
        chara_18 = new QLabel(centralwidget);
        chara_18->setObjectName("chara_18");
        chara_18->setGeometry(QRect(330, 180, 44, 41));
        chara_18->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_18->setScaledContents(true);
        chara_19 = new QLabel(centralwidget);
        chara_19->setObjectName("chara_19");
        chara_19->setGeometry(QRect(330, 220, 44, 41));
        chara_19->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_19->setScaledContents(true);
        chara_20 = new QLabel(centralwidget);
        chara_20->setObjectName("chara_20");
        chara_20->setGeometry(QRect(330, 260, 44, 41));
        chara_20->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_20->setScaledContents(true);
        chara_21 = new QLabel(centralwidget);
        chara_21->setObjectName("chara_21");
        chara_21->setGeometry(QRect(330, 290, 44, 41));
        chara_21->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_21->setScaledContents(true);
        chara_22 = new QLabel(centralwidget);
        chara_22->setObjectName("chara_22");
        chara_22->setGeometry(QRect(370, 290, 44, 41));
        chara_22->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_22->setScaledContents(true);
        chara_29 = new QLabel(centralwidget);
        chara_29->setObjectName("chara_29");
        chara_29->setGeometry(QRect(410, 290, 44, 41));
        chara_29->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_29->setScaledContents(true);
        chara_33 = new QLabel(centralwidget);
        chara_33->setObjectName("chara_33");
        chara_33->setGeometry(QRect(450, 290, 44, 41));
        chara_33->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_33->setScaledContents(true);
        chara_34 = new QLabel(centralwidget);
        chara_34->setObjectName("chara_34");
        chara_34->setGeometry(QRect(490, 290, 44, 41));
        chara_34->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_34->setScaledContents(true);
        chara_35 = new QLabel(centralwidget);
        chara_35->setObjectName("chara_35");
        chara_35->setGeometry(QRect(450, 250, 44, 41));
        chara_35->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_35->setScaledContents(true);
        chara_36 = new QLabel(centralwidget);
        chara_36->setObjectName("chara_36");
        chara_36->setGeometry(QRect(490, 250, 44, 41));
        chara_36->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_36->setScaledContents(true);
        chara_37 = new QLabel(centralwidget);
        chara_37->setObjectName("chara_37");
        chara_37->setGeometry(QRect(330, 250, 44, 41));
        chara_37->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_37->setScaledContents(true);
        chara_38 = new QLabel(centralwidget);
        chara_38->setObjectName("chara_38");
        chara_38->setGeometry(QRect(410, 250, 44, 41));
        chara_38->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_38->setScaledContents(true);
        chara_39 = new QLabel(centralwidget);
        chara_39->setObjectName("chara_39");
        chara_39->setGeometry(QRect(370, 250, 44, 41));
        chara_39->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_39->setScaledContents(true);
        chara_40 = new QLabel(centralwidget);
        chara_40->setObjectName("chara_40");
        chara_40->setGeometry(QRect(330, 210, 44, 41));
        chara_40->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_40->setScaledContents(true);
        chara_41 = new QLabel(centralwidget);
        chara_41->setObjectName("chara_41");
        chara_41->setGeometry(QRect(410, 210, 44, 41));
        chara_41->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_41->setScaledContents(true);
        chara_42 = new QLabel(centralwidget);
        chara_42->setObjectName("chara_42");
        chara_42->setGeometry(QRect(490, 210, 44, 41));
        chara_42->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_42->setScaledContents(true);
        chara_43 = new QLabel(centralwidget);
        chara_43->setObjectName("chara_43");
        chara_43->setGeometry(QRect(370, 210, 44, 41));
        chara_43->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_43->setScaledContents(true);
        chara_44 = new QLabel(centralwidget);
        chara_44->setObjectName("chara_44");
        chara_44->setGeometry(QRect(450, 210, 44, 41));
        chara_44->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_44->setScaledContents(true);
        chara_45 = new QLabel(centralwidget);
        chara_45->setObjectName("chara_45");
        chara_45->setGeometry(QRect(340, 170, 44, 41));
        chara_45->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_45->setScaledContents(true);
        chara_46 = new QLabel(centralwidget);
        chara_46->setObjectName("chara_46");
        chara_46->setGeometry(QRect(460, 170, 44, 41));
        chara_46->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_46->setScaledContents(true);
        chara_47 = new QLabel(centralwidget);
        chara_47->setObjectName("chara_47");
        chara_47->setGeometry(QRect(380, 170, 44, 41));
        chara_47->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_47->setScaledContents(true);
        chara_48 = new QLabel(centralwidget);
        chara_48->setObjectName("chara_48");
        chara_48->setGeometry(QRect(500, 170, 44, 41));
        chara_48->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_48->setScaledContents(true);
        chara_49 = new QLabel(centralwidget);
        chara_49->setObjectName("chara_49");
        chara_49->setGeometry(QRect(420, 170, 44, 41));
        chara_49->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_49->setScaledContents(true);
        chara_50 = new QLabel(centralwidget);
        chara_50->setObjectName("chara_50");
        chara_50->setGeometry(QRect(330, 130, 44, 41));
        chara_50->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_50->setScaledContents(true);
        chara_51 = new QLabel(centralwidget);
        chara_51->setObjectName("chara_51");
        chara_51->setGeometry(QRect(450, 130, 44, 41));
        chara_51->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_51->setScaledContents(true);
        chara_52 = new QLabel(centralwidget);
        chara_52->setObjectName("chara_52");
        chara_52->setGeometry(QRect(410, 130, 44, 41));
        chara_52->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_52->setScaledContents(true);
        chara_53 = new QLabel(centralwidget);
        chara_53->setObjectName("chara_53");
        chara_53->setGeometry(QRect(490, 130, 44, 41));
        chara_53->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_53->setScaledContents(true);
        chara_54 = new QLabel(centralwidget);
        chara_54->setObjectName("chara_54");
        chara_54->setGeometry(QRect(370, 130, 44, 41));
        chara_54->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_54->setScaledContents(true);
        chara_55 = new QLabel(centralwidget);
        chara_55->setObjectName("chara_55");
        chara_55->setGeometry(QRect(380, 90, 44, 41));
        chara_55->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_55->setScaledContents(true);
        chara_56 = new QLabel(centralwidget);
        chara_56->setObjectName("chara_56");
        chara_56->setGeometry(QRect(420, 90, 44, 41));
        chara_56->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_56->setScaledContents(true);
        chara_57 = new QLabel(centralwidget);
        chara_57->setObjectName("chara_57");
        chara_57->setGeometry(QRect(340, 90, 44, 41));
        chara_57->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_57->setScaledContents(true);
        chara_58 = new QLabel(centralwidget);
        chara_58->setObjectName("chara_58");
        chara_58->setGeometry(QRect(460, 90, 44, 41));
        chara_58->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_58->setScaledContents(true);
        chara_59 = new QLabel(centralwidget);
        chara_59->setObjectName("chara_59");
        chara_59->setGeometry(QRect(500, 90, 44, 41));
        chara_59->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_59->setScaledContents(true);
        chara_60 = new QLabel(centralwidget);
        chara_60->setObjectName("chara_60");
        chara_60->setGeometry(QRect(420, 50, 44, 41));
        chara_60->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_60->setScaledContents(true);
        chara_61 = new QLabel(centralwidget);
        chara_61->setObjectName("chara_61");
        chara_61->setGeometry(QRect(500, 50, 44, 41));
        chara_61->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_61->setScaledContents(true);
        chara_62 = new QLabel(centralwidget);
        chara_62->setObjectName("chara_62");
        chara_62->setGeometry(QRect(380, 50, 44, 41));
        chara_62->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_62->setScaledContents(true);
        chara_63 = new QLabel(centralwidget);
        chara_63->setObjectName("chara_63");
        chara_63->setGeometry(QRect(340, 50, 44, 41));
        chara_63->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_63->setScaledContents(true);
        chara_64 = new QLabel(centralwidget);
        chara_64->setObjectName("chara_64");
        chara_64->setGeometry(QRect(460, 50, 44, 41));
        chara_64->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_64->setScaledContents(true);
        chara_65 = new QLabel(centralwidget);
        chara_65->setObjectName("chara_65");
        chara_65->setGeometry(QRect(330, 10, 44, 41));
        chara_65->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_65->setScaledContents(true);
        chara_66 = new QLabel(centralwidget);
        chara_66->setObjectName("chara_66");
        chara_66->setGeometry(QRect(410, 10, 44, 41));
        chara_66->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_66->setScaledContents(true);
        chara_67 = new QLabel(centralwidget);
        chara_67->setObjectName("chara_67");
        chara_67->setGeometry(QRect(370, 10, 44, 41));
        chara_67->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_67->setScaledContents(true);
        chara_68 = new QLabel(centralwidget);
        chara_68->setObjectName("chara_68");
        chara_68->setGeometry(QRect(450, 10, 44, 41));
        chara_68->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_68->setScaledContents(true);
        chara_69 = new QLabel(centralwidget);
        chara_69->setObjectName("chara_69");
        chara_69->setGeometry(QRect(490, 10, 44, 41));
        chara_69->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_69->setScaledContents(true);
        chara_70 = new QLabel(centralwidget);
        chara_70->setObjectName("chara_70");
        chara_70->setGeometry(QRect(420, 0, 44, 41));
        chara_70->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_70->setScaledContents(true);
        chara_71 = new QLabel(centralwidget);
        chara_71->setObjectName("chara_71");
        chara_71->setGeometry(QRect(340, 0, 44, 41));
        chara_71->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_71->setScaledContents(true);
        chara_72 = new QLabel(centralwidget);
        chara_72->setObjectName("chara_72");
        chara_72->setGeometry(QRect(380, 0, 44, 41));
        chara_72->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_72->setScaledContents(true);
        chara_73 = new QLabel(centralwidget);
        chara_73->setObjectName("chara_73");
        chara_73->setGeometry(QRect(500, 0, 44, 41));
        chara_73->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_73->setScaledContents(true);
        chara_74 = new QLabel(centralwidget);
        chara_74->setObjectName("chara_74");
        chara_74->setGeometry(QRect(460, 0, 44, 41));
        chara_74->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_74->setScaledContents(true);
        chara_75 = new QLabel(centralwidget);
        chara_75->setObjectName("chara_75");
        chara_75->setGeometry(QRect(-10, 0, 44, 41));
        chara_75->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_75->setScaledContents(true);
        chara_76 = new QLabel(centralwidget);
        chara_76->setObjectName("chara_76");
        chara_76->setGeometry(QRect(110, 0, 44, 41));
        chara_76->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_76->setScaledContents(true);
        chara_77 = new QLabel(centralwidget);
        chara_77->setObjectName("chara_77");
        chara_77->setGeometry(QRect(70, 0, 44, 41));
        chara_77->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_77->setScaledContents(true);
        chara_78 = new QLabel(centralwidget);
        chara_78->setObjectName("chara_78");
        chara_78->setGeometry(QRect(150, 0, 44, 41));
        chara_78->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_78->setScaledContents(true);
        chara_79 = new QLabel(centralwidget);
        chara_79->setObjectName("chara_79");
        chara_79->setGeometry(QRect(30, 0, 44, 41));
        chara_79->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_79->setScaledContents(true);
        chara_80 = new QLabel(centralwidget);
        chara_80->setObjectName("chara_80");
        chara_80->setGeometry(QRect(80, 40, 44, 41));
        chara_80->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_80->setScaledContents(true);
        chara_81 = new QLabel(centralwidget);
        chara_81->setObjectName("chara_81");
        chara_81->setGeometry(QRect(120, 40, 44, 41));
        chara_81->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_81->setScaledContents(true);
        chara_82 = new QLabel(centralwidget);
        chara_82->setObjectName("chara_82");
        chara_82->setGeometry(QRect(160, 40, 44, 41));
        chara_82->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_82->setScaledContents(true);
        chara_83 = new QLabel(centralwidget);
        chara_83->setObjectName("chara_83");
        chara_83->setGeometry(QRect(40, 40, 44, 41));
        chara_83->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_83->setScaledContents(true);
        chara_84 = new QLabel(centralwidget);
        chara_84->setObjectName("chara_84");
        chara_84->setGeometry(QRect(0, 40, 44, 41));
        chara_84->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_84->setScaledContents(true);
        chara_85 = new QLabel(centralwidget);
        chara_85->setObjectName("chara_85");
        chara_85->setGeometry(QRect(120, 80, 44, 41));
        chara_85->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_85->setScaledContents(true);
        chara_86 = new QLabel(centralwidget);
        chara_86->setObjectName("chara_86");
        chara_86->setGeometry(QRect(40, 80, 44, 41));
        chara_86->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_86->setScaledContents(true);
        chara_87 = new QLabel(centralwidget);
        chara_87->setObjectName("chara_87");
        chara_87->setGeometry(QRect(0, 80, 44, 41));
        chara_87->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_87->setScaledContents(true);
        chara_88 = new QLabel(centralwidget);
        chara_88->setObjectName("chara_88");
        chara_88->setGeometry(QRect(160, 80, 44, 41));
        chara_88->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_88->setScaledContents(true);
        chara_89 = new QLabel(centralwidget);
        chara_89->setObjectName("chara_89");
        chara_89->setGeometry(QRect(80, 80, 44, 41));
        chara_89->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_89->setScaledContents(true);
        chara_90 = new QLabel(centralwidget);
        chara_90->setObjectName("chara_90");
        chara_90->setGeometry(QRect(160, 120, 44, 41));
        chara_90->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_90->setScaledContents(true);
        chara_91 = new QLabel(centralwidget);
        chara_91->setObjectName("chara_91");
        chara_91->setGeometry(QRect(80, 120, 44, 41));
        chara_91->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_91->setScaledContents(true);
        chara_92 = new QLabel(centralwidget);
        chara_92->setObjectName("chara_92");
        chara_92->setGeometry(QRect(0, 120, 44, 41));
        chara_92->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_92->setScaledContents(true);
        chara_93 = new QLabel(centralwidget);
        chara_93->setObjectName("chara_93");
        chara_93->setGeometry(QRect(120, 120, 44, 41));
        chara_93->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_93->setScaledContents(true);
        chara_94 = new QLabel(centralwidget);
        chara_94->setObjectName("chara_94");
        chara_94->setGeometry(QRect(40, 120, 44, 41));
        chara_94->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_94->setScaledContents(true);
        chara_95 = new QLabel(centralwidget);
        chara_95->setObjectName("chara_95");
        chara_95->setGeometry(QRect(80, 160, 44, 41));
        chara_95->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_95->setScaledContents(true);
        chara_96 = new QLabel(centralwidget);
        chara_96->setObjectName("chara_96");
        chara_96->setGeometry(QRect(120, 160, 44, 41));
        chara_96->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_96->setScaledContents(true);
        chara_97 = new QLabel(centralwidget);
        chara_97->setObjectName("chara_97");
        chara_97->setGeometry(QRect(160, 160, 44, 41));
        chara_97->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_97->setScaledContents(true);
        chara_98 = new QLabel(centralwidget);
        chara_98->setObjectName("chara_98");
        chara_98->setGeometry(QRect(40, 160, 44, 41));
        chara_98->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_98->setScaledContents(true);
        chara_99 = new QLabel(centralwidget);
        chara_99->setObjectName("chara_99");
        chara_99->setGeometry(QRect(0, 160, 44, 41));
        chara_99->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_99->setScaledContents(true);
        chara_100 = new QLabel(centralwidget);
        chara_100->setObjectName("chara_100");
        chara_100->setGeometry(QRect(80, 200, 44, 41));
        chara_100->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_100->setScaledContents(true);
        chara_101 = new QLabel(centralwidget);
        chara_101->setObjectName("chara_101");
        chara_101->setGeometry(QRect(40, 200, 44, 41));
        chara_101->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_101->setScaledContents(true);
        chara_102 = new QLabel(centralwidget);
        chara_102->setObjectName("chara_102");
        chara_102->setGeometry(QRect(0, 200, 44, 41));
        chara_102->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_102->setScaledContents(true);
        chara_103 = new QLabel(centralwidget);
        chara_103->setObjectName("chara_103");
        chara_103->setGeometry(QRect(160, 200, 44, 41));
        chara_103->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_103->setScaledContents(true);
        chara_104 = new QLabel(centralwidget);
        chara_104->setObjectName("chara_104");
        chara_104->setGeometry(QRect(120, 200, 44, 41));
        chara_104->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_104->setScaledContents(true);
        chara_105 = new QLabel(centralwidget);
        chara_105->setObjectName("chara_105");
        chara_105->setGeometry(QRect(0, 240, 44, 41));
        chara_105->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_105->setScaledContents(true);
        chara_106 = new QLabel(centralwidget);
        chara_106->setObjectName("chara_106");
        chara_106->setGeometry(QRect(40, 240, 44, 41));
        chara_106->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_106->setScaledContents(true);
        chara_107 = new QLabel(centralwidget);
        chara_107->setObjectName("chara_107");
        chara_107->setGeometry(QRect(80, 240, 44, 41));
        chara_107->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_107->setScaledContents(true);
        chara_108 = new QLabel(centralwidget);
        chara_108->setObjectName("chara_108");
        chara_108->setGeometry(QRect(160, 240, 44, 41));
        chara_108->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_108->setScaledContents(true);
        chara_109 = new QLabel(centralwidget);
        chara_109->setObjectName("chara_109");
        chara_109->setGeometry(QRect(120, 240, 44, 41));
        chara_109->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_109->setScaledContents(true);
        chara_110 = new QLabel(centralwidget);
        chara_110->setObjectName("chara_110");
        chara_110->setGeometry(QRect(40, 280, 44, 41));
        chara_110->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_110->setScaledContents(true);
        chara_111 = new QLabel(centralwidget);
        chara_111->setObjectName("chara_111");
        chara_111->setGeometry(QRect(160, 280, 44, 41));
        chara_111->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_111->setScaledContents(true);
        chara_112 = new QLabel(centralwidget);
        chara_112->setObjectName("chara_112");
        chara_112->setGeometry(QRect(0, 280, 44, 41));
        chara_112->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_112->setScaledContents(true);
        chara_113 = new QLabel(centralwidget);
        chara_113->setObjectName("chara_113");
        chara_113->setGeometry(QRect(120, 280, 44, 41));
        chara_113->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_113->setScaledContents(true);
        chara_114 = new QLabel(centralwidget);
        chara_114->setObjectName("chara_114");
        chara_114->setGeometry(QRect(80, 280, 44, 41));
        chara_114->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_114->setScaledContents(true);
        chara_115 = new QLabel(centralwidget);
        chara_115->setObjectName("chara_115");
        chara_115->setGeometry(QRect(40, 290, 44, 41));
        chara_115->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_115->setScaledContents(true);
        chara_116 = new QLabel(centralwidget);
        chara_116->setObjectName("chara_116");
        chara_116->setGeometry(QRect(80, 290, 44, 41));
        chara_116->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_116->setScaledContents(true);
        chara_117 = new QLabel(centralwidget);
        chara_117->setObjectName("chara_117");
        chara_117->setGeometry(QRect(120, 290, 44, 41));
        chara_117->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_117->setScaledContents(true);
        chara_118 = new QLabel(centralwidget);
        chara_118->setObjectName("chara_118");
        chara_118->setGeometry(QRect(0, 290, 44, 41));
        chara_118->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_118->setScaledContents(true);
        chara_119 = new QLabel(centralwidget);
        chara_119->setObjectName("chara_119");
        chara_119->setGeometry(QRect(160, 290, 44, 41));
        chara_119->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector - copia (6).jpg")));
        chara_119->setScaledContents(true);
        arbusto9 = new QLabel(centralwidget);
        arbusto9->setObjectName("arbusto9");
        arbusto9->setGeometry(QRect(90, 290, 21, 21));
        arbusto9->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia-removebg-preview.png")));
        arbusto9->setScaledContents(true);
        arbusto3 = new QLabel(centralwidget);
        arbusto3->setObjectName("arbusto3");
        arbusto3->setGeometry(QRect(380, 40, 31, 31));
        arbusto3->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia-removebg-preview.png")));
        arbusto3->setScaledContents(true);
        arbusto4 = new QLabel(centralwidget);
        arbusto4->setObjectName("arbusto4");
        arbusto4->setGeometry(QRect(100, 10, 31, 31));
        arbusto4->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia__7_-removebg-preview.png")));
        arbusto4->setScaledContents(true);
        arbusto8 = new QLabel(centralwidget);
        arbusto8->setObjectName("arbusto8");
        arbusto8->setGeometry(QRect(350, 290, 31, 31));
        arbusto8->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia__7_-removebg-preview.png")));
        arbusto8->setScaledContents(true);
        arbusto5 = new QLabel(centralwidget);
        arbusto5->setObjectName("arbusto5");
        arbusto5->setGeometry(QRect(100, 140, 31, 31));
        arbusto5->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia__7_-removebg-preview.png")));
        arbusto5->setScaledContents(true);
        arbusto6 = new QLabel(centralwidget);
        arbusto6->setObjectName("arbusto6");
        arbusto6->setGeometry(QRect(370, 160, 31, 31));
        arbusto6->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia__5_-removebg-preview.png")));
        arbusto6->setScaledContents(true);
        arbusto7 = new QLabel(centralwidget);
        arbusto7->setObjectName("arbusto7");
        arbusto7->setGeometry(QRect(140, 210, 31, 31));
        arbusto7->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia__5_-removebg-preview.png")));
        arbusto7->setScaledContents(true);
        arbusto1 = new QLabel(centralwidget);
        arbusto1->setObjectName("arbusto1");
        arbusto1->setGeometry(QRect(160, 30, 31, 31));
        arbusto1->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia__5_-removebg-preview.png")));
        arbusto1->setScaledContents(true);
        arbusto2 = new QLabel(centralwidget);
        arbusto2->setObjectName("arbusto2");
        arbusto2->setGeometry(QRect(320, 10, 41, 31));
        arbusto2->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector_-_copia__5_-removebg-preview.png")));
        arbusto2->setScaledContents(true);
        semaforo = new QLabel(centralwidget);
        semaforo->setObjectName("semaforo");
        semaforo->setGeometry(QRect(290, 0, 21, 31));
        semaforo->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/da-removebg-preview (2).png")));
        semaforo->setScaledContents(true);
        semaforo_2 = new QLabel(centralwidget);
        semaforo_2->setObjectName("semaforo_2");
        semaforo_2->setGeometry(QRect(195, -3, 21, 31));
        semaforo_2->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/da-removebg-preview (2).png")));
        semaforo_2->setScaledContents(true);
        enemy = new QLabel(centralwidget);
        enemy->setObjectName("enemy");
        enemy->setGeometry(QRect(212, -11, 25, 32));
        enemy->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector-removebg-preview.png")));
        enemy->setScaledContents(true);
        enemy_2 = new QLabel(centralwidget);
        enemy_2->setObjectName("enemy_2");
        enemy_2->setGeometry(QRect(265, -100, 25, 32));
        enemy_2->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector-removebg-preview.png")));
        enemy_2->setScaledContents(true);
        enemy_3 = new QLabel(centralwidget);
        enemy_3->setObjectName("enemy_3");
        enemy_3->setGeometry(QRect(229, -200, 25, 32));
        enemy_3->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector-removebg-preview.png")));
        enemy_3->setScaledContents(true);
        yellow = new QLabel(centralwidget);
        yellow->setObjectName("yellow");
        yellow->setGeometry(QRect(276, -400, 22, 28));
        yellow->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/pixel-race-arcade-game-top-view-8-bit-car-racing-vector__1_-removebg-preview.png")));
        yellow->setScaledContents(true);
        arbusto5_2 = new QLabel(centralwidget);
        arbusto5_2->setObjectName("arbusto5_2");
        arbusto5_2->setGeometry(QRect(-10, 260, 51, 71));
        arbusto5_2->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_2->setScaledContents(true);
        arbusto5_3 = new QLabel(centralwidget);
        arbusto5_3->setObjectName("arbusto5_3");
        arbusto5_3->setGeometry(QRect(17, 260, 51, 71));
        arbusto5_3->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_3->setScaledContents(true);
        arbusto5_4 = new QLabel(centralwidget);
        arbusto5_4->setObjectName("arbusto5_4");
        arbusto5_4->setGeometry(QRect(40, 260, 51, 71));
        arbusto5_4->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_4->setScaledContents(true);
        arbusto5_5 = new QLabel(centralwidget);
        arbusto5_5->setObjectName("arbusto5_5");
        arbusto5_5->setGeometry(QRect(-10, 210, 51, 71));
        arbusto5_5->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_5->setScaledContents(true);
        arbusto5_6 = new QLabel(centralwidget);
        arbusto5_6->setObjectName("arbusto5_6");
        arbusto5_6->setGeometry(QRect(40, 220, 51, 71));
        arbusto5_6->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_6->setScaledContents(true);
        arbusto5_7 = new QLabel(centralwidget);
        arbusto5_7->setObjectName("arbusto5_7");
        arbusto5_7->setGeometry(QRect(20, 220, 51, 71));
        arbusto5_7->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_7->setScaledContents(true);
        arbusto5_8 = new QLabel(centralwidget);
        arbusto5_8->setObjectName("arbusto5_8");
        arbusto5_8->setGeometry(QRect(-10, 140, 51, 71));
        arbusto5_8->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_8->setScaledContents(true);
        arbusto5_9 = new QLabel(centralwidget);
        arbusto5_9->setObjectName("arbusto5_9");
        arbusto5_9->setGeometry(QRect(40, 140, 51, 71));
        arbusto5_9->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_9->setScaledContents(true);
        arbusto5_10 = new QLabel(centralwidget);
        arbusto5_10->setObjectName("arbusto5_10");
        arbusto5_10->setGeometry(QRect(20, 170, 51, 71));
        arbusto5_10->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_10->setScaledContents(true);
        arbusto5_11 = new QLabel(centralwidget);
        arbusto5_11->setObjectName("arbusto5_11");
        arbusto5_11->setGeometry(QRect(20, 130, 51, 71));
        arbusto5_11->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_11->setScaledContents(true);
        arbusto5_12 = new QLabel(centralwidget);
        arbusto5_12->setObjectName("arbusto5_12");
        arbusto5_12->setGeometry(QRect(-10, 170, 51, 71));
        arbusto5_12->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_12->setScaledContents(true);
        arbusto5_13 = new QLabel(centralwidget);
        arbusto5_13->setObjectName("arbusto5_13");
        arbusto5_13->setGeometry(QRect(40, 170, 51, 71));
        arbusto5_13->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_13->setScaledContents(true);
        arbusto5_14 = new QLabel(centralwidget);
        arbusto5_14->setObjectName("arbusto5_14");
        arbusto5_14->setGeometry(QRect(20, 140, 51, 71));
        arbusto5_14->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_14->setScaledContents(true);
        arbusto5_15 = new QLabel(centralwidget);
        arbusto5_15->setObjectName("arbusto5_15");
        arbusto5_15->setGeometry(QRect(-10, -10, 51, 71));
        arbusto5_15->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_15->setScaledContents(true);
        arbusto5_16 = new QLabel(centralwidget);
        arbusto5_16->setObjectName("arbusto5_16");
        arbusto5_16->setGeometry(QRect(-10, 30, 51, 71));
        arbusto5_16->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_16->setScaledContents(true);
        arbusto5_17 = new QLabel(centralwidget);
        arbusto5_17->setObjectName("arbusto5_17");
        arbusto5_17->setGeometry(QRect(-10, 80, 51, 71));
        arbusto5_17->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_17->setScaledContents(true);
        arbusto5_18 = new QLabel(centralwidget);
        arbusto5_18->setObjectName("arbusto5_18");
        arbusto5_18->setGeometry(QRect(-10, 110, 51, 71));
        arbusto5_18->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_18->setScaledContents(true);
        arbusto5_19 = new QLabel(centralwidget);
        arbusto5_19->setObjectName("arbusto5_19");
        arbusto5_19->setGeometry(QRect(430, -10, 51, 71));
        arbusto5_19->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_19->setScaledContents(true);
        arbusto5_20 = new QLabel(centralwidget);
        arbusto5_20->setObjectName("arbusto5_20");
        arbusto5_20->setGeometry(QRect(430, 40, 51, 71));
        arbusto5_20->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_20->setScaledContents(true);
        arbusto5_21 = new QLabel(centralwidget);
        arbusto5_21->setObjectName("arbusto5_21");
        arbusto5_21->setGeometry(QRect(430, 90, 51, 71));
        arbusto5_21->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_21->setScaledContents(true);
        arbusto5_22 = new QLabel(centralwidget);
        arbusto5_22->setObjectName("arbusto5_22");
        arbusto5_22->setGeometry(QRect(430, 140, 51, 71));
        arbusto5_22->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_22->setScaledContents(true);
        arbusto5_23 = new QLabel(centralwidget);
        arbusto5_23->setObjectName("arbusto5_23");
        arbusto5_23->setGeometry(QRect(430, 190, 51, 71));
        arbusto5_23->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_23->setScaledContents(true);
        arbusto5_24 = new QLabel(centralwidget);
        arbusto5_24->setObjectName("arbusto5_24");
        arbusto5_24->setGeometry(QRect(430, 240, 51, 71));
        arbusto5_24->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_24->setScaledContents(true);
        arbusto5_25 = new QLabel(centralwidget);
        arbusto5_25->setObjectName("arbusto5_25");
        arbusto5_25->setGeometry(QRect(430, 270, 51, 71));
        arbusto5_25->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_25->setScaledContents(true);
        arbusto5_26 = new QLabel(centralwidget);
        arbusto5_26->setObjectName("arbusto5_26");
        arbusto5_26->setGeometry(QRect(460, -10, 51, 71));
        arbusto5_26->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_26->setScaledContents(true);
        arbusto5_27 = new QLabel(centralwidget);
        arbusto5_27->setObjectName("arbusto5_27");
        arbusto5_27->setGeometry(QRect(460, 40, 51, 71));
        arbusto5_27->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_27->setScaledContents(true);
        arbusto5_28 = new QLabel(centralwidget);
        arbusto5_28->setObjectName("arbusto5_28");
        arbusto5_28->setGeometry(QRect(460, 90, 51, 71));
        arbusto5_28->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_28->setScaledContents(true);
        arbusto5_29 = new QLabel(centralwidget);
        arbusto5_29->setObjectName("arbusto5_29");
        arbusto5_29->setGeometry(QRect(460, 140, 51, 71));
        arbusto5_29->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_29->setScaledContents(true);
        arbusto5_30 = new QLabel(centralwidget);
        arbusto5_30->setObjectName("arbusto5_30");
        arbusto5_30->setGeometry(QRect(460, 190, 51, 71));
        arbusto5_30->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_30->setScaledContents(true);
        arbusto5_31 = new QLabel(centralwidget);
        arbusto5_31->setObjectName("arbusto5_31");
        arbusto5_31->setGeometry(QRect(460, 240, 51, 71));
        arbusto5_31->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_31->setScaledContents(true);
        arbusto5_32 = new QLabel(centralwidget);
        arbusto5_32->setObjectName("arbusto5_32");
        arbusto5_32->setGeometry(QRect(460, 280, 51, 71));
        arbusto5_32->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_32->setScaledContents(true);
        arbusto5_33 = new QLabel(centralwidget);
        arbusto5_33->setObjectName("arbusto5_33");
        arbusto5_33->setGeometry(QRect(490, -10, 51, 71));
        arbusto5_33->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_33->setScaledContents(true);
        arbusto5_34 = new QLabel(centralwidget);
        arbusto5_34->setObjectName("arbusto5_34");
        arbusto5_34->setGeometry(QRect(490, 40, 51, 71));
        arbusto5_34->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_34->setScaledContents(true);
        arbusto5_35 = new QLabel(centralwidget);
        arbusto5_35->setObjectName("arbusto5_35");
        arbusto5_35->setGeometry(QRect(490, 90, 51, 71));
        arbusto5_35->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_35->setScaledContents(true);
        arbusto5_36 = new QLabel(centralwidget);
        arbusto5_36->setObjectName("arbusto5_36");
        arbusto5_36->setGeometry(QRect(490, 140, 51, 71));
        arbusto5_36->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_36->setScaledContents(true);
        arbusto5_37 = new QLabel(centralwidget);
        arbusto5_37->setObjectName("arbusto5_37");
        arbusto5_37->setGeometry(QRect(490, 190, 51, 71));
        arbusto5_37->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_37->setScaledContents(true);
        arbusto5_38 = new QLabel(centralwidget);
        arbusto5_38->setObjectName("arbusto5_38");
        arbusto5_38->setGeometry(QRect(490, 230, 51, 71));
        arbusto5_38->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_38->setScaledContents(true);
        arbusto5_39 = new QLabel(centralwidget);
        arbusto5_39->setObjectName("arbusto5_39");
        arbusto5_39->setGeometry(QRect(490, 270, 51, 71));
        arbusto5_39->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_39->setScaledContents(true);
        arbusto5_40 = new QLabel(centralwidget);
        arbusto5_40->setObjectName("arbusto5_40");
        arbusto5_40->setGeometry(QRect(130, 100, 21, 41));
        arbusto5_40->setScaledContents(true);
        arbusto5_41 = new QLabel(centralwidget);
        arbusto5_41->setObjectName("arbusto5_41");
        arbusto5_41->setGeometry(QRect(20, -10, 51, 71));
        arbusto5_41->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_41->setScaledContents(true);
        arbusto5_42 = new QLabel(centralwidget);
        arbusto5_42->setObjectName("arbusto5_42");
        arbusto5_42->setGeometry(QRect(40, -10, 51, 71));
        arbusto5_42->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_42->setScaledContents(true);
        arbusto5_43 = new QLabel(centralwidget);
        arbusto5_43->setObjectName("arbusto5_43");
        arbusto5_43->setGeometry(QRect(20, 40, 51, 71));
        arbusto5_43->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_43->setScaledContents(true);
        arbusto5_44 = new QLabel(centralwidget);
        arbusto5_44->setObjectName("arbusto5_44");
        arbusto5_44->setGeometry(QRect(40, 40, 51, 71));
        arbusto5_44->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_44->setScaledContents(true);
        arbusto5_45 = new QLabel(centralwidget);
        arbusto5_45->setObjectName("arbusto5_45");
        arbusto5_45->setGeometry(QRect(20, 90, 51, 71));
        arbusto5_45->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_45->setScaledContents(true);
        arbusto5_46 = new QLabel(centralwidget);
        arbusto5_46->setObjectName("arbusto5_46");
        arbusto5_46->setGeometry(QRect(40, 90, 51, 71));
        arbusto5_46->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/descarga-removebg-preview.png")));
        arbusto5_46->setScaledContents(true);
        arbusto6_2 = new QLabel(centralwidget);
        arbusto6_2->setObjectName("arbusto6_2");
        arbusto6_2->setGeometry(QRect(140, 80, 31, 21));
        arbusto6_2->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/forest_tiles_spritesheet_by_clothieredward_de5dhzd-pre_-_copia__6_-removebg-preview.png")));
        arbusto6_2->setScaledContents(true);
        arbusto6_3 = new QLabel(centralwidget);
        arbusto6_3->setObjectName("arbusto6_3");
        arbusto6_3->setGeometry(QRect(380, 110, 31, 21));
        arbusto6_3->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/forest_tiles_spritesheet_by_clothieredward_de5dhzd-pre_-_copia__6_-removebg-preview.png")));
        arbusto6_3->setScaledContents(true);
        arbusto6_4 = new QLabel(centralwidget);
        arbusto6_4->setObjectName("arbusto6_4");
        arbusto6_4->setGeometry(QRect(300, 270, 16, 21));
        arbusto6_4->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/forest_tiles_spritesheet_by_clothieredward_de5dhzd-pre-removebg-preview.png")));
        arbusto6_4->setScaledContents(true);
        arbusto6_5 = new QLabel(centralwidget);
        arbusto6_5->setObjectName("arbusto6_5");
        arbusto6_5->setGeometry(QRect(180, 160, 16, 21));
        arbusto6_5->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/forest_tiles_spritesheet_by_clothieredward_de5dhzd-pre-removebg-preview.png")));
        arbusto6_5->setScaledContents(true);
        arbusto6_6 = new QLabel(centralwidget);
        arbusto6_6->setObjectName("arbusto6_6");
        arbusto6_6->setGeometry(QRect(310, 80, 16, 21));
        arbusto6_6->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/forest_tiles_spritesheet_by_clothieredward_de5dhzd-pre-removebg-preview.png")));
        arbusto6_6->setScaledContents(true);
        arbusto6_7 = new QLabel(centralwidget);
        arbusto6_7->setObjectName("arbusto6_7");
        arbusto6_7->setGeometry(QRect(130, 120, 31, 21));
        arbusto6_7->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/forest_tiles_spritesheet_by_clothieredward_de5dhzd-pre_-_copia-removebg-preview.png")));
        arbusto6_7->setScaledContents(true);
        arbusto6_8 = new QLabel(centralwidget);
        arbusto6_8->setObjectName("arbusto6_8");
        arbusto6_8->setGeometry(QRect(340, 140, 31, 21));
        arbusto6_8->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/forest_tiles_spritesheet_by_clothieredward_de5dhzd-pre_-_copia-removebg-preview.png")));
        arbusto6_8->setScaledContents(true);
        arbusto6_9 = new QLabel(centralwidget);
        arbusto6_9->setObjectName("arbusto6_9");
        arbusto6_9->setGeometry(QRect(140, 270, 31, 21));
        arbusto6_9->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/forest_tiles_spritesheet_by_clothieredward_de5dhzd-pre_-_copia-removebg-preview.png")));
        arbusto6_9->setScaledContents(true);
        arbusto6_10 = new QLabel(centralwidget);
        arbusto6_10->setObjectName("arbusto6_10");
        arbusto6_10->setGeometry(QRect(340, 60, 31, 21));
        arbusto6_10->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/forest_tiles_spritesheet_by_clothieredward_de5dhzd-pre_-_copia-removebg-preview.png")));
        arbusto6_10->setScaledContents(true);
        arbusto6_11 = new QLabel(centralwidget);
        arbusto6_11->setObjectName("arbusto6_11");
        arbusto6_11->setGeometry(QRect(320, 230, 31, 21));
        arbusto6_11->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/forest_tiles_spritesheet_by_clothieredward_de5dhzd-pre_-_copia__6_-removebg-preview.png")));
        arbusto6_11->setScaledContents(true);
        point = new QLabel(centralwidget);
        point->setObjectName("point");
        point->setGeometry(QRect(455, 0, 71, 21));
        QFont font;
        font.setPointSize(17);
        point->setFont(font);
        point->setStyleSheet(QString::fromUtf8("QLabel{\n"
"color:white;\n"
"\n"
"}"));
        point->setScaledContents(true);
        menu = new QLabel(centralwidget);
        menu->setObjectName("menu");
        menu->setGeometry(QRect(180, 110, 161, 111));
        menu->setFont(font);
        menu->setStyleSheet(QString::fromUtf8("QLabel{\n"
"color:white;\n"
"\n"
"}"));
        menu->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/damaged-cars-after-collision-on-the-road-pixel-vector-46427653.jpg")));
        menu->setScaledContents(true);
        exit = new QPushButton(centralwidget);
        exit->setObjectName("exit");
        exit->setGeometry(QRect(180, 220, 80, 18));
        QFont font1;
        font1.setBold(true);
        exit->setFont(font1);
        exit->setStyleSheet(QString::fromUtf8("QPushButton {\n"
"    background-color: #061117; /* Color de fondo normal */\n"
"    color: white; /* Color de texto normal */\n"
"}\n"
"\n"
"/* Estilo para el QPushButton cuando el mouse est\303\241 sobre \303\251l (hover) */\n"
"QPushButton:hover {\n"
"    background-color: #DF2929 ; /* Cambia el color de fondo al hacer hover */\n"
"    color: black; /* Cambia el color de texto al hacer hover */\n"
"}"));
        play = new QPushButton(centralwidget);
        play->setObjectName("play");
        play->setGeometry(QRect(260, 220, 80, 18));
        play->setFont(font1);
        play->setStyleSheet(QString::fromUtf8("QPushButton {\n"
"    background-color: #061117; /* Color de fondo normal */\n"
"    color: white; /* Color de texto normal */\n"
"}\n"
"\n"
"/* Estilo para el QPushButton cuando el mouse est\303\241 sobre \303\251l (hover) */\n"
"QPushButton:hover {\n"
"    background-color: #34590F ; /* Cambia el color de fondo al hacer hover */\n"
"    color: black; /* Cambia el color de texto al hacer hover */\n"
"}"));
        xplositon = new QLabel(centralwidget);
        xplositon->setObjectName("xplositon");
        xplositon->setGeometry(QRect(150, 240, 21, 21));
        xplositon->setFont(font);
        xplositon->setStyleSheet(QString::fromUtf8("QLabel{\n"
"color:white;\n"
"\n"
"}"));
        xplositon->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/carros/png-transparent-explosion-sprite-explosion-leaf-maple-leaf-orange-removebg-preview.png")));
        xplositon->setScaledContents(true);
        paint->setCentralWidget(centralwidget);
        arbusto5_11->raise();
        chara_2->raise();
        chara_3->raise();
        chara_4->raise();
        chara_5->raise();
        chara_6->raise();
        chara_7->raise();
        chara_8->raise();
        chara_9->raise();
        chara_10->raise();
        chara_11->raise();
        chara_12->raise();
        chara_23->raise();
        chara_24->raise();
        chara_25->raise();
        chara_26->raise();
        chara_27->raise();
        chara_28->raise();
        chara_30->raise();
        chara_31->raise();
        chara_32->raise();
        chara->raise();
        chara_13->raise();
        chara_14->raise();
        chara_15->raise();
        chara_16->raise();
        chara_17->raise();
        chara_18->raise();
        chara_19->raise();
        chara_20->raise();
        chara_21->raise();
        chara_22->raise();
        chara_29->raise();
        chara_33->raise();
        chara_34->raise();
        chara_35->raise();
        chara_36->raise();
        chara_37->raise();
        chara_38->raise();
        chara_39->raise();
        chara_40->raise();
        chara_41->raise();
        chara_42->raise();
        chara_43->raise();
        chara_44->raise();
        chara_45->raise();
        chara_46->raise();
        chara_47->raise();
        chara_48->raise();
        chara_49->raise();
        chara_50->raise();
        chara_51->raise();
        chara_52->raise();
        chara_53->raise();
        chara_54->raise();
        chara_55->raise();
        chara_56->raise();
        chara_57->raise();
        chara_58->raise();
        chara_59->raise();
        chara_60->raise();
        chara_61->raise();
        chara_62->raise();
        chara_63->raise();
        chara_64->raise();
        chara_65->raise();
        chara_66->raise();
        chara_67->raise();
        chara_68->raise();
        chara_69->raise();
        chara_70->raise();
        chara_71->raise();
        chara_72->raise();
        chara_73->raise();
        chara_74->raise();
        chara_75->raise();
        chara_76->raise();
        chara_77->raise();
        chara_78->raise();
        chara_79->raise();
        chara_80->raise();
        chara_81->raise();
        chara_82->raise();
        chara_83->raise();
        chara_84->raise();
        chara_85->raise();
        chara_86->raise();
        chara_87->raise();
        chara_88->raise();
        chara_89->raise();
        chara_90->raise();
        chara_91->raise();
        chara_92->raise();
        chara_93->raise();
        chara_94->raise();
        chara_95->raise();
        chara_96->raise();
        chara_97->raise();
        chara_98->raise();
        chara_99->raise();
        chara_100->raise();
        chara_101->raise();
        chara_102->raise();
        chara_103->raise();
        chara_104->raise();
        chara_105->raise();
        chara_106->raise();
        chara_107->raise();
        chara_108->raise();
        chara_109->raise();
        chara_110->raise();
        chara_111->raise();
        chara_112->raise();
        chara_113->raise();
        chara_114->raise();
        chara_115->raise();
        chara_116->raise();
        chara_117->raise();
        chara_118->raise();
        chara_119->raise();
        arbusto9->raise();
        arbusto3->raise();
        arbusto4->raise();
        arbusto8->raise();
        arbusto5->raise();
        arbusto6->raise();
        arbusto7->raise();
        arbusto1->raise();
        arbusto2->raise();
        arbusto5_15->raise();
        arbusto5_16->raise();
        arbusto5_17->raise();
        arbusto5_18->raise();
        arbusto5_8->raise();
        arbusto5_12->raise();
        arbusto5_5->raise();
        arbusto5_2->raise();
        arbusto5_19->raise();
        arbusto5_20->raise();
        arbusto5_21->raise();
        arbusto5_22->raise();
        arbusto5_23->raise();
        arbusto5_24->raise();
        arbusto5_25->raise();
        arbusto5_26->raise();
        arbusto5_27->raise();
        arbusto5_28->raise();
        arbusto5_29->raise();
        arbusto5_30->raise();
        arbusto5_31->raise();
        arbusto5_32->raise();
        arbusto5_33->raise();
        arbusto5_34->raise();
        arbusto5_35->raise();
        arbusto5_36->raise();
        arbusto5_37->raise();
        arbusto5_38->raise();
        arbusto5_39->raise();
        enemy_3->raise();
        enemy->raise();
        enemy_2->raise();
        yellow->raise();
        semaforo->raise();
        semaforo_2->raise();
        arbusto5_40->raise();
        arbusto5_41->raise();
        arbusto5_42->raise();
        arbusto5_43->raise();
        arbusto5_44->raise();
        arbusto5_45->raise();
        arbusto5_46->raise();
        arbusto5_14->raise();
        arbusto5_9->raise();
        arbusto5_10->raise();
        arbusto5_13->raise();
        arbusto5_6->raise();
        arbusto5_7->raise();
        arbusto5_3->raise();
        arbusto5_4->raise();
        arbusto6_2->raise();
        arbusto6_3->raise();
        arbusto6_4->raise();
        arbusto6_5->raise();
        arbusto6_6->raise();
        arbusto6_7->raise();
        arbusto6_8->raise();
        arbusto6_9->raise();
        arbusto6_10->raise();
        arbusto6_11->raise();
        point->raise();
        menu->raise();
        exit->raise();
        play->raise();
        xplositon->raise();
        statusbar = new QStatusBar(paint);
        statusbar->setObjectName("statusbar");
        paint->setStatusBar(statusbar);

        retranslateUi(paint);

        QMetaObject::connectSlotsByName(paint);
    } // setupUi

    void retranslateUi(QMainWindow *paint)
    {
        paint->setWindowTitle(QCoreApplication::translate("paint", "paint", nullptr));
        chara->setText(QString());
        chara_2->setText(QString());
        chara_3->setText(QString());
        chara_4->setText(QString());
        chara_5->setText(QString());
        chara_6->setText(QString());
        chara_7->setText(QString());
        chara_8->setText(QString());
        chara_9->setText(QString());
        chara_10->setText(QString());
        chara_11->setText(QString());
        chara_12->setText(QString());
        chara_23->setText(QString());
        chara_24->setText(QString());
        chara_25->setText(QString());
        chara_26->setText(QString());
        chara_27->setText(QString());
        chara_28->setText(QString());
        chara_30->setText(QString());
        chara_31->setText(QString());
        chara_32->setText(QString());
        chara_13->setText(QString());
        chara_14->setText(QString());
        chara_15->setText(QString());
        chara_16->setText(QString());
        chara_17->setText(QString());
        chara_18->setText(QString());
        chara_19->setText(QString());
        chara_20->setText(QString());
        chara_21->setText(QString());
        chara_22->setText(QString());
        chara_29->setText(QString());
        chara_33->setText(QString());
        chara_34->setText(QString());
        chara_35->setText(QString());
        chara_36->setText(QString());
        chara_37->setText(QString());
        chara_38->setText(QString());
        chara_39->setText(QString());
        chara_40->setText(QString());
        chara_41->setText(QString());
        chara_42->setText(QString());
        chara_43->setText(QString());
        chara_44->setText(QString());
        chara_45->setText(QString());
        chara_46->setText(QString());
        chara_47->setText(QString());
        chara_48->setText(QString());
        chara_49->setText(QString());
        chara_50->setText(QString());
        chara_51->setText(QString());
        chara_52->setText(QString());
        chara_53->setText(QString());
        chara_54->setText(QString());
        chara_55->setText(QString());
        chara_56->setText(QString());
        chara_57->setText(QString());
        chara_58->setText(QString());
        chara_59->setText(QString());
        chara_60->setText(QString());
        chara_61->setText(QString());
        chara_62->setText(QString());
        chara_63->setText(QString());
        chara_64->setText(QString());
        chara_65->setText(QString());
        chara_66->setText(QString());
        chara_67->setText(QString());
        chara_68->setText(QString());
        chara_69->setText(QString());
        chara_70->setText(QString());
        chara_71->setText(QString());
        chara_72->setText(QString());
        chara_73->setText(QString());
        chara_74->setText(QString());
        chara_75->setText(QString());
        chara_76->setText(QString());
        chara_77->setText(QString());
        chara_78->setText(QString());
        chara_79->setText(QString());
        chara_80->setText(QString());
        chara_81->setText(QString());
        chara_82->setText(QString());
        chara_83->setText(QString());
        chara_84->setText(QString());
        chara_85->setText(QString());
        chara_86->setText(QString());
        chara_87->setText(QString());
        chara_88->setText(QString());
        chara_89->setText(QString());
        chara_90->setText(QString());
        chara_91->setText(QString());
        chara_92->setText(QString());
        chara_93->setText(QString());
        chara_94->setText(QString());
        chara_95->setText(QString());
        chara_96->setText(QString());
        chara_97->setText(QString());
        chara_98->setText(QString());
        chara_99->setText(QString());
        chara_100->setText(QString());
        chara_101->setText(QString());
        chara_102->setText(QString());
        chara_103->setText(QString());
        chara_104->setText(QString());
        chara_105->setText(QString());
        chara_106->setText(QString());
        chara_107->setText(QString());
        chara_108->setText(QString());
        chara_109->setText(QString());
        chara_110->setText(QString());
        chara_111->setText(QString());
        chara_112->setText(QString());
        chara_113->setText(QString());
        chara_114->setText(QString());
        chara_115->setText(QString());
        chara_116->setText(QString());
        chara_117->setText(QString());
        chara_118->setText(QString());
        chara_119->setText(QString());
        arbusto9->setText(QString());
        arbusto3->setText(QString());
        arbusto4->setText(QString());
        arbusto8->setText(QString());
        arbusto5->setText(QString());
        arbusto6->setText(QString());
        arbusto7->setText(QString());
        arbusto1->setText(QString());
        arbusto2->setText(QString());
        semaforo->setText(QString());
        semaforo_2->setText(QString());
        enemy->setText(QString());
        enemy_2->setText(QString());
        enemy_3->setText(QString());
        yellow->setText(QString());
        arbusto5_2->setText(QString());
        arbusto5_3->setText(QString());
        arbusto5_4->setText(QString());
        arbusto5_5->setText(QString());
        arbusto5_6->setText(QString());
        arbusto5_7->setText(QString());
        arbusto5_8->setText(QString());
        arbusto5_9->setText(QString());
        arbusto5_10->setText(QString());
        arbusto5_11->setText(QString());
        arbusto5_12->setText(QString());
        arbusto5_13->setText(QString());
        arbusto5_14->setText(QString());
        arbusto5_15->setText(QString());
        arbusto5_16->setText(QString());
        arbusto5_17->setText(QString());
        arbusto5_18->setText(QString());
        arbusto5_19->setText(QString());
        arbusto5_20->setText(QString());
        arbusto5_21->setText(QString());
        arbusto5_22->setText(QString());
        arbusto5_23->setText(QString());
        arbusto5_24->setText(QString());
        arbusto5_25->setText(QString());
        arbusto5_26->setText(QString());
        arbusto5_27->setText(QString());
        arbusto5_28->setText(QString());
        arbusto5_29->setText(QString());
        arbusto5_30->setText(QString());
        arbusto5_31->setText(QString());
        arbusto5_32->setText(QString());
        arbusto5_33->setText(QString());
        arbusto5_34->setText(QString());
        arbusto5_35->setText(QString());
        arbusto5_36->setText(QString());
        arbusto5_37->setText(QString());
        arbusto5_38->setText(QString());
        arbusto5_39->setText(QString());
        arbusto5_40->setText(QString());
        arbusto5_41->setText(QString());
        arbusto5_42->setText(QString());
        arbusto5_43->setText(QString());
        arbusto5_44->setText(QString());
        arbusto5_45->setText(QString());
        arbusto5_46->setText(QString());
        arbusto6_2->setText(QString());
        arbusto6_3->setText(QString());
        arbusto6_4->setText(QString());
        arbusto6_5->setText(QString());
        arbusto6_6->setText(QString());
        arbusto6_7->setText(QString());
        arbusto6_8->setText(QString());
        arbusto6_9->setText(QString());
        arbusto6_10->setText(QString());
        arbusto6_11->setText(QString());
        point->setText(QCoreApplication::translate("paint", "0", nullptr));
        menu->setText(QString());
        exit->setText(QCoreApplication::translate("paint", "EXIT", nullptr));
        play->setText(QCoreApplication::translate("paint", "PLAY", nullptr));
        xplositon->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class paint: public Ui_paint {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PAINT_H
